# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

barrier_option_price <- function(nInt, strike, spot, vol, r, expiry, barrier, nReps) {
    .Call(`_BarrierOptionPricer_barrier_option_price`, nInt, strike, spot, vol, r, expiry, barrier, nReps)
}

